global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus_master'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node_exporter_rockylinux'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9100','172.19.14.136:9100']
  - job_name: 'postgresql_exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['172.19.14.136:9187']
  - job_name: 'Blackbox-HTTP'
    scrape_interval: 15s
    metrics_path: /probe
    params:
      module:
      - http_2xx
    relabel_configs:
    - source_labels:
      - __address__
      target_label: __param_target
    - source_labels:
      - __param_target
      target_label: instance
    - replacement: 172.19.14.136:9115
      target_label: __address__
    static_configs:
      - targets:
        - http://172.19.14.136:9115

